### ISSUE TITLE
Create database to store all data on the website.

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#18]
# Create Database
To make the pages as clean as possible without looking clustered, to make the resource links easily maintainable.

## Task
- [x] create a database folder to store all the .js files that will contain the links of all resources on the pages.
- [x] add a .js file for a list of careers path available, in progress and coming soon to the database and feed it to the home page and careers page.
- [x] add .js file for the MVPs list in the contribute page to the database and feed it to the contribute page.
