### ISSUE TITLE
Add table of content to the Contributing.md

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#44]
# Add Table of Content
Add a Table of Content for the Contributing file which also serves as a link to the corresponding sections in the file such that when the user clicks on one of the links, it will take them directly to that section in the Contributing file.

## Task 
- [ ] create a Table of Content for the Contributions.md.
- [ ]  each item in the Table of Content should link to each section when the user clicks on it.
- [ ]  the table of content should be placed immediately before the **No Code Contributions** section.

## Resources.
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.
Learn how to use [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#html).

**Comment by anthonychinwe** [comment]
I would like to work on this @Timonwa
