### ISSUE TITLE
Create a Table of Content for the Readme.md

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#8]
# Add Table of Content
Create a **Table of Content** for the Readme file which also serves as a link to the corresponding sections in the file such that when the user clicks on one of the links, it will take them directly to that section in the **Readme** file.

Also, add a **Back to Top** link at the end of each section. This link will take the user back to the table of content.

The table of content should be placed immediately above the **About Project** section.

This issue is divided into 2 Tasks and you can only do one per pull request.

## Task 1
- [x] create a **Table of Content** for the **Readme** file.
- [x] each item in the **Table of Content** should link to each section when the user clicks on it.
- [x] the table of content should be placed immediately before the **About Project** section.

## Task 2
- [ ] create a **Back to Top** link directly below each section.
- [ ] the **Back to Top** should take the user back to the Table of Content.

## Resources.
- View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.
- Learn how to use [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#html).
