### ISSUE TITLE
Add resources that talk about choosing a career in tech. 

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#9]
# Add Resource to Career page
On the Careers page, there is a section with the title **Learn About the Tech Careers**. Currently, there are only 2 resources covering that and we need more to add to it.

## Task
- [x] 2 to 3 relevant YouTube videos that talk about the different careers in tech.
- [x] 2 to 3 relevant YouTube videos that talk about the different no code careers in tech.  
- [x] 2 to 3 relevant YouTube videos that talk about how to choose a career in tech
- [x] 1 more relevant article that talks about the different career opportunities in tech.
- [x] 1 to 2 relevant articles that talk about how to choose a tech career.

## Things to note:
- when adding your links, the resources on the different careers in tech must come before the resources on how to choose a career in tech in each subsection.
- only add videos or articles that are relevant and useful.
- you can only choose a maximum of 2 tasks from the above, this is to allow others to contribute to this project.
- please be as descriptive as possible when naming your links and do not forget to include the author or creator of the content.
Eg. "21 no-code tech jobs you can do to become a tech sis or tech bro. ~ Timonwa" 

## Resources
- View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by ipeavy** [comment]
Hey can I be assigned to the first task?

**Comment by Timonwa** [comment]
Yes, you can go ahead with the first task.

**Comment by codewithfan** [comment]
Hi Timonwa, 

I would like to add three videos on career paths in tech. Videos are 2021 and current. May I be assigned to do?

<img width="1227" alt="Screen Shot 2022-03-26 at 12 57 36 PM" src="https://user-images.githubusercontent.com/85418632/160223892-aa11f3d2-074a-4418-92b4-ecf415bfe4f4.png">

Thank you.

**Comment by Timonwa** [comment]
Yes you can go ahead @codewithfan

**Comment by anthonychinwe** [comment]
Hello @Timonwa, I would like to do the second task in this issue if that's okay

**Comment by anant-strong** [comment]
hey @Timonwa, I would like to contribute to the third task in this issue if that's okay

**Comment by Timonwa** [comment]
Yes @anant-strong . You can go ahead with the 3rd task.

**Comment by anant-strong** [comment]
These are the two articles that I think are good
1. https://www.business.com/articles/best-careers-tech-geeks/
2. https://www.freecodecamp.org/news/how-to-choose-the-best-tech-career-path-for-you-61c4d5ff9a77/

**Comment by Timonwa** [comment]
yes you can add these links @anant-strong.
